/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Base64Encoder: typeof import('./src/components/encoder/Base64Encoder.vue')['default']
    BCPassword: typeof import('./src/components/security/BCPassword.vue')['default']
    ContentValueTab: typeof import('./src/components/content/ContentValueTab.vue')['default']
    DateConvert: typeof import('./src/components/convert/DateConvert.vue')['default']
    DevContentPane: typeof import('./src/components/content/DevContentPane.vue')['default']
    HashGenerator: typeof import('./src/components/generators/HashGenerator.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HTMLEncoder: typeof import('./src/components/encoder/HTMLEncoder.vue')['default']
    IPComponent: typeof import('./src/components/network/IPComponent.vue')['default']
    JSONConvert: typeof import('./src/components/convert/JSONConvert.vue')['default']
    JWTEncoder: typeof import('./src/components/encoder/JWTEncoder.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCalendar: typeof import('naive-ui')['NCalendar']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NTree: typeof import('naive-ui')['NTree']
    Properties: typeof import('./src/components/icons/Properties.vue')['default']
    PropertiesConvert: typeof import('./src/components/convert/PropertiesConvert.vue')['default']
    QRCodeReader: typeof import('./src/components/graphic/QRCodeReader.vue')['default']
    ResizeableWrapper: typeof import('./src/components/common/ResizeableWrapper.vue')['default']
    Ribbon: typeof import('./src/components/sidebar/Ribbon.vue')['default']
    Server: typeof import('./src/components/icons/Server.vue')['default']
    ToolbarControlWidget: typeof import('./src/components/common/ToolbarControlWidget.vue')['default']
    TraceRouteComponent: typeof import('./src/components/network/TraceRouteComponent.vue')['default']
    URLEncoder: typeof import('./src/components/encoder/URLEncoder.vue')['default']
    WindowClose: typeof import('./src/components/icons/WindowClose.vue')['default']
    WindowMax: typeof import('./src/components/icons/WindowMax.vue')['default']
    WindowMin: typeof import('./src/components/icons/WindowMin.vue')['default']
    WindowRestore: typeof import('./src/components/icons/WindowRestore.vue')['default']
  }
}
